# Generated by Django 2.0.13 on 2019-04-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressBookList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('cnumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
