# Generated by Django 2.2 on 2019-04-03 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0002_addressbooklist_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbooklist',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='addressbooklist',
            name='cnumber',
            field=models.CharField(max_length=12, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='addressbooklist',
            name='fname',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='addressbooklist',
            name='lname',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
    ]
