# Generated by Django 2.0.13 on 2019-04-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0003_auto_20190403_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressbooklist',
            name='cnumber',
            field=models.CharField(max_length=12, unique=True, verbose_name='Contact Number'),
        ),
    ]
